quarkus:
  datasource:
    db-kind: postgresql
    username: ${DB_USER:graphql}
    password: ${DB_PASSWORD:graphql}
    reactive:
      url: vertx-reactive:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_DATABASE:graphql}