version: '3.8'
services:
  # postgres + pgadmin4 web UI
  postgres:
    container_name: postgres
    # 14.3
    image: docker.io/postgres:15.2-alpine3.17
    volumes:
      - ${REMOTE_PROJECT_PATH:-.}/postgres/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d/:ro
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
      POSTGRES_MULTIPLE_DATABASES: graphql
    ports:
      - "5432:5432"
    networks:
      - default
      - database
  pgadmin4:
    container_name: pgadmin4
    # 6.9
    image: docker.io/dpage/pgadmin4:7.1
    profiles:
      - dev
    volumes:
      - ${REMOTE_PROJECT_PATH:-.}/pgadmin4/pgadmin4/servers.json:/pgadmin4/servers.json:ro
    depends_on:
      - postgres
    ports:
      - "8091:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: pgadmin4
    networks:
      - database

networks:
  default:
    driver: bridge
  database: